/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ActivationCodeId = IDL.Nat;
export const Timestamp = IDL.Int;
export const ActivationCode = IDL.Record({
  'id' : ActivationCodeId,
  'expiryDate' : Timestamp,
  'code' : IDL.Text,
  'usedAt' : IDL.Opt(Timestamp),
  'usedBy' : IDL.Opt(IDL.Text),
  'used' : IDL.Bool,
});
export const AdminLogId = IDL.Nat;
export const AdminLog = IDL.Record({
  'id' : AdminLogId,
  'action' : IDL.Text,
  'target' : IDL.Text,
  'timestamp' : Timestamp,
  'details' : IDL.Text,
  'adminId' : IDL.Text,
});
export const CustomerId = IDL.Nat;
export const CustomerStatus = IDL.Variant({
  'active' : IDL.Null,
  'banned' : IDL.Null,
  'suspended' : IDL.Null,
});
export const Customer = IDL.Record({
  'id' : CustomerId,
  'status' : CustomerStatus,
  'joinDate' : Timestamp,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'walletBalance' : IDL.Int,
  'totalRides' : IDL.Nat,
});
export const DriverId = IDL.Nat;
export const DriverStatus = IDL.Variant({
  'blocked' : IDL.Null,
  'suspended' : IDL.Null,
  'offline' : IDL.Null,
  'onRide' : IDL.Null,
  'online' : IDL.Null,
});
export const VehicleType = IDL.Variant({
  'Car' : IDL.Null,
  'Premium' : IDL.Null,
  'Bike' : IDL.Null,
  'Rickshaw' : IDL.Null,
});
export const DriverRank = IDL.Variant({
  'Diamond' : IDL.Null,
  'Gold' : IDL.Null,
  'Platinum' : IDL.Null,
});
export const Driver = IDL.Record({
  'id' : DriverId,
  'status' : DriverStatus,
  'vehicleType' : VehicleType,
  'vehiclePlate' : IDL.Text,
  'cnic' : IDL.Text,
  'name' : IDL.Text,
  'rank' : DriverRank,
  'vehicleModel' : IDL.Text,
  'licenseNumber' : IDL.Text,
  'vehicleColor' : IDL.Text,
  'rating' : IDL.Float64,
  'phone' : IDL.Text,
  'activationCode' : IDL.Text,
  'walletBalance' : IDL.Int,
  'totalRides' : IDL.Nat,
});
export const PromoCodeId = IDL.Nat;
export const PromoStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const DiscountType = IDL.Variant({
  'fixed' : IDL.Null,
  'percentage' : IDL.Null,
});
export const PromoCode = IDL.Record({
  'id' : PromoCodeId,
  'status' : PromoStatus,
  'expiryDate' : Timestamp,
  'code' : IDL.Text,
  'discountAmount' : IDL.Int,
  'discountType' : DiscountType,
  'usageCount' : IDL.Nat,
  'usageLimit' : IDL.Nat,
});
export const RideId = IDL.Nat;
export const RideStatus = IDL.Variant({
  'reached' : IDL.Null,
  'cancelled' : IDL.Null,
  'started' : IDL.Null,
  'completed' : IDL.Null,
  'arriving' : IDL.Null,
  'accepted' : IDL.Null,
  'inProgress' : IDL.Null,
  'searching' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'cash' : IDL.Null,
  'jazzCash' : IDL.Null,
  'easypaisa' : IDL.Null,
  'wallet' : IDL.Null,
});
export const Ride = IDL.Record({
  'id' : RideId,
  'otp' : IDL.Text,
  'status' : RideStatus,
  'dropLat' : IDL.Float64,
  'dropLng' : IDL.Float64,
  'completedAt' : IDL.Opt(Timestamp),
  'driverId' : IDL.Opt(DriverId),
  'vehicleType' : VehicleType,
  'paymentMethod' : PaymentMethod,
  'driverRating' : IDL.Opt(IDL.Nat),
  'pickupLat' : IDL.Float64,
  'pickupLng' : IDL.Float64,
  'createdAt' : Timestamp,
  'customerRating' : IDL.Opt(IDL.Nat),
  'totalFare' : IDL.Int,
  'pickupAddress' : IDL.Text,
  'customerId' : CustomerId,
  'dropAddress' : IDL.Text,
  'distanceFare' : IDL.Int,
  'baseFare' : IDL.Int,
});
export const Wallet = IDL.Record({
  'driverId' : DriverId,
  'totalEarned' : IDL.Int,
  'lastUpdated' : Timestamp,
  'commissionOwed' : IDL.Int,
  'netBalance' : IDL.Int,
});

export const idlService = IDL.Service({
  'addActivationCode' : IDL.Func([ActivationCode], [ActivationCode], []),
  'addAdminLog' : IDL.Func([AdminLog], [AdminLog], []),
  'addCustomer' : IDL.Func([Customer], [Customer], []),
  'addDriver' : IDL.Func([Driver], [Driver], []),
  'addPromoCode' : IDL.Func([PromoCode], [PromoCode], []),
  'addRide' : IDL.Func([Ride], [Ride], []),
  'getCustomer' : IDL.Func([CustomerId], [IDL.Opt(Customer)], ['query']),
  'getDriver' : IDL.Func([DriverId], [IDL.Opt(Driver)], ['query']),
  'getRide' : IDL.Func([RideId], [IDL.Opt(Ride)], ['query']),
  'getWallet' : IDL.Func([DriverId], [IDL.Opt(Wallet)], ['query']),
  'listActivationCodes' : IDL.Func([], [IDL.Vec(ActivationCode)], ['query']),
  'listAdminLogs' : IDL.Func([], [IDL.Vec(AdminLog)], ['query']),
  'listCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'listDrivers' : IDL.Func([], [IDL.Vec(Driver)], ['query']),
  'listPromoCodes' : IDL.Func([], [IDL.Vec(PromoCode)], ['query']),
  'listRides' : IDL.Func([], [IDL.Vec(Ride)], ['query']),
  'listWallets' : IDL.Func([], [IDL.Vec(Wallet)], ['query']),
  'updateCustomer' : IDL.Func(
      [Customer],
      [IDL.Variant({ 'ok' : IDL.Null, 'notFound' : IDL.Null })],
      [],
    ),
  'updateDriver' : IDL.Func(
      [Driver],
      [IDL.Variant({ 'ok' : IDL.Null, 'notFound' : IDL.Null })],
      [],
    ),
  'updatePromoCode' : IDL.Func(
      [PromoCode],
      [IDL.Variant({ 'ok' : IDL.Null, 'notFound' : IDL.Null })],
      [],
    ),
  'updateRideStatus' : IDL.Func(
      [
        RideId,
        RideStatus,
        IDL.Opt(Timestamp),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(DriverId),
      ],
      [IDL.Variant({ 'ok' : IDL.Null, 'notFound' : IDL.Null })],
      [],
    ),
  'updateWallet' : IDL.Func([Wallet], [Wallet], []),
  'useActivationCode' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Variant({
          'ok' : ActivationCode,
          'alreadyUsed' : IDL.Null,
          'expired' : IDL.Null,
          'notFound' : IDL.Null,
        }),
      ],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ActivationCodeId = IDL.Nat;
  const Timestamp = IDL.Int;
  const ActivationCode = IDL.Record({
    'id' : ActivationCodeId,
    'expiryDate' : Timestamp,
    'code' : IDL.Text,
    'usedAt' : IDL.Opt(Timestamp),
    'usedBy' : IDL.Opt(IDL.Text),
    'used' : IDL.Bool,
  });
  const AdminLogId = IDL.Nat;
  const AdminLog = IDL.Record({
    'id' : AdminLogId,
    'action' : IDL.Text,
    'target' : IDL.Text,
    'timestamp' : Timestamp,
    'details' : IDL.Text,
    'adminId' : IDL.Text,
  });
  const CustomerId = IDL.Nat;
  const CustomerStatus = IDL.Variant({
    'active' : IDL.Null,
    'banned' : IDL.Null,
    'suspended' : IDL.Null,
  });
  const Customer = IDL.Record({
    'id' : CustomerId,
    'status' : CustomerStatus,
    'joinDate' : Timestamp,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'walletBalance' : IDL.Int,
    'totalRides' : IDL.Nat,
  });
  const DriverId = IDL.Nat;
  const DriverStatus = IDL.Variant({
    'blocked' : IDL.Null,
    'suspended' : IDL.Null,
    'offline' : IDL.Null,
    'onRide' : IDL.Null,
    'online' : IDL.Null,
  });
  const VehicleType = IDL.Variant({
    'Car' : IDL.Null,
    'Premium' : IDL.Null,
    'Bike' : IDL.Null,
    'Rickshaw' : IDL.Null,
  });
  const DriverRank = IDL.Variant({
    'Diamond' : IDL.Null,
    'Gold' : IDL.Null,
    'Platinum' : IDL.Null,
  });
  const Driver = IDL.Record({
    'id' : DriverId,
    'status' : DriverStatus,
    'vehicleType' : VehicleType,
    'vehiclePlate' : IDL.Text,
    'cnic' : IDL.Text,
    'name' : IDL.Text,
    'rank' : DriverRank,
    'vehicleModel' : IDL.Text,
    'licenseNumber' : IDL.Text,
    'vehicleColor' : IDL.Text,
    'rating' : IDL.Float64,
    'phone' : IDL.Text,
    'activationCode' : IDL.Text,
    'walletBalance' : IDL.Int,
    'totalRides' : IDL.Nat,
  });
  const PromoCodeId = IDL.Nat;
  const PromoStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const DiscountType = IDL.Variant({
    'fixed' : IDL.Null,
    'percentage' : IDL.Null,
  });
  const PromoCode = IDL.Record({
    'id' : PromoCodeId,
    'status' : PromoStatus,
    'expiryDate' : Timestamp,
    'code' : IDL.Text,
    'discountAmount' : IDL.Int,
    'discountType' : DiscountType,
    'usageCount' : IDL.Nat,
    'usageLimit' : IDL.Nat,
  });
  const RideId = IDL.Nat;
  const RideStatus = IDL.Variant({
    'reached' : IDL.Null,
    'cancelled' : IDL.Null,
    'started' : IDL.Null,
    'completed' : IDL.Null,
    'arriving' : IDL.Null,
    'accepted' : IDL.Null,
    'inProgress' : IDL.Null,
    'searching' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'cash' : IDL.Null,
    'jazzCash' : IDL.Null,
    'easypaisa' : IDL.Null,
    'wallet' : IDL.Null,
  });
  const Ride = IDL.Record({
    'id' : RideId,
    'otp' : IDL.Text,
    'status' : RideStatus,
    'dropLat' : IDL.Float64,
    'dropLng' : IDL.Float64,
    'completedAt' : IDL.Opt(Timestamp),
    'driverId' : IDL.Opt(DriverId),
    'vehicleType' : VehicleType,
    'paymentMethod' : PaymentMethod,
    'driverRating' : IDL.Opt(IDL.Nat),
    'pickupLat' : IDL.Float64,
    'pickupLng' : IDL.Float64,
    'createdAt' : Timestamp,
    'customerRating' : IDL.Opt(IDL.Nat),
    'totalFare' : IDL.Int,
    'pickupAddress' : IDL.Text,
    'customerId' : CustomerId,
    'dropAddress' : IDL.Text,
    'distanceFare' : IDL.Int,
    'baseFare' : IDL.Int,
  });
  const Wallet = IDL.Record({
    'driverId' : DriverId,
    'totalEarned' : IDL.Int,
    'lastUpdated' : Timestamp,
    'commissionOwed' : IDL.Int,
    'netBalance' : IDL.Int,
  });
  
  return IDL.Service({
    'addActivationCode' : IDL.Func([ActivationCode], [ActivationCode], []),
    'addAdminLog' : IDL.Func([AdminLog], [AdminLog], []),
    'addCustomer' : IDL.Func([Customer], [Customer], []),
    'addDriver' : IDL.Func([Driver], [Driver], []),
    'addPromoCode' : IDL.Func([PromoCode], [PromoCode], []),
    'addRide' : IDL.Func([Ride], [Ride], []),
    'getCustomer' : IDL.Func([CustomerId], [IDL.Opt(Customer)], ['query']),
    'getDriver' : IDL.Func([DriverId], [IDL.Opt(Driver)], ['query']),
    'getRide' : IDL.Func([RideId], [IDL.Opt(Ride)], ['query']),
    'getWallet' : IDL.Func([DriverId], [IDL.Opt(Wallet)], ['query']),
    'listActivationCodes' : IDL.Func([], [IDL.Vec(ActivationCode)], ['query']),
    'listAdminLogs' : IDL.Func([], [IDL.Vec(AdminLog)], ['query']),
    'listCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'listDrivers' : IDL.Func([], [IDL.Vec(Driver)], ['query']),
    'listPromoCodes' : IDL.Func([], [IDL.Vec(PromoCode)], ['query']),
    'listRides' : IDL.Func([], [IDL.Vec(Ride)], ['query']),
    'listWallets' : IDL.Func([], [IDL.Vec(Wallet)], ['query']),
    'updateCustomer' : IDL.Func(
        [Customer],
        [IDL.Variant({ 'ok' : IDL.Null, 'notFound' : IDL.Null })],
        [],
      ),
    'updateDriver' : IDL.Func(
        [Driver],
        [IDL.Variant({ 'ok' : IDL.Null, 'notFound' : IDL.Null })],
        [],
      ),
    'updatePromoCode' : IDL.Func(
        [PromoCode],
        [IDL.Variant({ 'ok' : IDL.Null, 'notFound' : IDL.Null })],
        [],
      ),
    'updateRideStatus' : IDL.Func(
        [
          RideId,
          RideStatus,
          IDL.Opt(Timestamp),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(DriverId),
        ],
        [IDL.Variant({ 'ok' : IDL.Null, 'notFound' : IDL.Null })],
        [],
      ),
    'updateWallet' : IDL.Func([Wallet], [Wallet], []),
    'useActivationCode' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Variant({
            'ok' : ActivationCode,
            'alreadyUsed' : IDL.Null,
            'expired' : IDL.Null,
            'notFound' : IDL.Null,
          }),
        ],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };