/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivationCode {
  'id' : ActivationCodeId,
  'expiryDate' : Timestamp,
  'code' : string,
  'usedAt' : [] | [Timestamp],
  'usedBy' : [] | [string],
  'used' : boolean,
}
export type ActivationCodeId = bigint;
export interface AdminLog {
  'id' : AdminLogId,
  'action' : string,
  'target' : string,
  'timestamp' : Timestamp,
  'details' : string,
  'adminId' : string,
}
export type AdminLogId = bigint;
export interface Customer {
  'id' : CustomerId,
  'status' : CustomerStatus,
  'joinDate' : Timestamp,
  'name' : string,
  'email' : string,
  'phone' : string,
  'walletBalance' : bigint,
  'totalRides' : bigint,
}
export type CustomerId = bigint;
export type CustomerStatus = { 'active' : null } |
  { 'banned' : null } |
  { 'suspended' : null };
export type DiscountType = { 'fixed' : null } |
  { 'percentage' : null };
export interface Driver {
  'id' : DriverId,
  'status' : DriverStatus,
  'vehicleType' : VehicleType,
  'vehiclePlate' : string,
  'cnic' : string,
  'name' : string,
  'rank' : DriverRank,
  'vehicleModel' : string,
  'licenseNumber' : string,
  'vehicleColor' : string,
  'rating' : number,
  'phone' : string,
  'activationCode' : string,
  'walletBalance' : bigint,
  'totalRides' : bigint,
}
export type DriverId = bigint;
export type DriverRank = { 'Diamond' : null } |
  { 'Gold' : null } |
  { 'Platinum' : null };
export type DriverStatus = { 'blocked' : null } |
  { 'suspended' : null } |
  { 'offline' : null } |
  { 'onRide' : null } |
  { 'online' : null };
export type PaymentMethod = { 'cash' : null } |
  { 'jazzCash' : null } |
  { 'easypaisa' : null } |
  { 'wallet' : null };
export interface PromoCode {
  'id' : PromoCodeId,
  'status' : PromoStatus,
  'expiryDate' : Timestamp,
  'code' : string,
  'discountAmount' : bigint,
  'discountType' : DiscountType,
  'usageCount' : bigint,
  'usageLimit' : bigint,
}
export type PromoCodeId = bigint;
export type PromoStatus = { 'active' : null } |
  { 'inactive' : null };
export interface Ride {
  'id' : RideId,
  'otp' : string,
  'status' : RideStatus,
  'dropLat' : number,
  'dropLng' : number,
  'completedAt' : [] | [Timestamp],
  'driverId' : [] | [DriverId],
  'vehicleType' : VehicleType,
  'paymentMethod' : PaymentMethod,
  'driverRating' : [] | [bigint],
  'pickupLat' : number,
  'pickupLng' : number,
  'createdAt' : Timestamp,
  'customerRating' : [] | [bigint],
  'totalFare' : bigint,
  'pickupAddress' : string,
  'customerId' : CustomerId,
  'dropAddress' : string,
  'distanceFare' : bigint,
  'baseFare' : bigint,
}
export type RideId = bigint;
export type RideStatus = { 'reached' : null } |
  { 'cancelled' : null } |
  { 'started' : null } |
  { 'completed' : null } |
  { 'arriving' : null } |
  { 'accepted' : null } |
  { 'inProgress' : null } |
  { 'searching' : null };
export type Timestamp = bigint;
export type VehicleType = { 'Car' : null } |
  { 'Premium' : null } |
  { 'Bike' : null } |
  { 'Rickshaw' : null };
export interface Wallet {
  'driverId' : DriverId,
  'totalEarned' : bigint,
  'lastUpdated' : Timestamp,
  'commissionOwed' : bigint,
  'netBalance' : bigint,
}
export interface _SERVICE {
  'addActivationCode' : ActorMethod<[ActivationCode], ActivationCode>,
  'addAdminLog' : ActorMethod<[AdminLog], AdminLog>,
  'addCustomer' : ActorMethod<[Customer], Customer>,
  'addDriver' : ActorMethod<[Driver], Driver>,
  'addPromoCode' : ActorMethod<[PromoCode], PromoCode>,
  'addRide' : ActorMethod<[Ride], Ride>,
  'getCustomer' : ActorMethod<[CustomerId], [] | [Customer]>,
  'getDriver' : ActorMethod<[DriverId], [] | [Driver]>,
  'getRide' : ActorMethod<[RideId], [] | [Ride]>,
  'getWallet' : ActorMethod<[DriverId], [] | [Wallet]>,
  'listActivationCodes' : ActorMethod<[], Array<ActivationCode>>,
  'listAdminLogs' : ActorMethod<[], Array<AdminLog>>,
  'listCustomers' : ActorMethod<[], Array<Customer>>,
  'listDrivers' : ActorMethod<[], Array<Driver>>,
  'listPromoCodes' : ActorMethod<[], Array<PromoCode>>,
  'listRides' : ActorMethod<[], Array<Ride>>,
  'listWallets' : ActorMethod<[], Array<Wallet>>,
  'updateCustomer' : ActorMethod<
    [Customer],
    { 'ok' : null } |
      { 'notFound' : null }
  >,
  'updateDriver' : ActorMethod<
    [Driver],
    { 'ok' : null } |
      { 'notFound' : null }
  >,
  'updatePromoCode' : ActorMethod<
    [PromoCode],
    { 'ok' : null } |
      { 'notFound' : null }
  >,
  'updateRideStatus' : ActorMethod<
    [
      RideId,
      RideStatus,
      [] | [Timestamp],
      [] | [bigint],
      [] | [bigint],
      [] | [DriverId],
    ],
    { 'ok' : null } |
      { 'notFound' : null }
  >,
  'updateWallet' : ActorMethod<[Wallet], Wallet>,
  'useActivationCode' : ActorMethod<
    [string, string],
    { 'ok' : ActivationCode } |
      { 'alreadyUsed' : null } |
      { 'expired' : null } |
      { 'notFound' : null }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];