/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface PromoCode {
    id: PromoCodeId;
    status: PromoStatus;
    expiryDate: Timestamp;
    code: string;
    discountAmount: bigint;
    discountType: DiscountType;
    usageCount: bigint;
    usageLimit: bigint;
}
export interface Driver {
    id: DriverId;
    status: DriverStatus;
    vehicleType: VehicleType;
    vehiclePlate: string;
    cnic: string;
    name: string;
    rank: DriverRank;
    vehicleModel: string;
    licenseNumber: string;
    vehicleColor: string;
    rating: number;
    phone: string;
    activationCode: string;
    walletBalance: bigint;
    totalRides: bigint;
}
export type PromoCodeId = bigint;
export type ActivationCodeId = bigint;
export type RideId = bigint;
export type AdminLogId = bigint;
export interface Customer {
    id: CustomerId;
    status: CustomerStatus;
    joinDate: Timestamp;
    name: string;
    email: string;
    phone: string;
    walletBalance: bigint;
    totalRides: bigint;
}
export interface ActivationCode {
    id: ActivationCodeId;
    expiryDate: Timestamp;
    code: string;
    usedAt?: Timestamp;
    usedBy?: string;
    used: boolean;
}
export interface Wallet {
    driverId: DriverId;
    totalEarned: bigint;
    lastUpdated: Timestamp;
    commissionOwed: bigint;
    netBalance: bigint;
}
export interface Ride {
    id: RideId;
    otp: string;
    status: RideStatus;
    dropLat: number;
    dropLng: number;
    completedAt?: Timestamp;
    driverId?: DriverId;
    vehicleType: VehicleType;
    paymentMethod: PaymentMethod;
    driverRating?: bigint;
    pickupLat: number;
    pickupLng: number;
    createdAt: Timestamp;
    customerRating?: bigint;
    totalFare: bigint;
    pickupAddress: string;
    customerId: CustomerId;
    dropAddress: string;
    distanceFare: bigint;
    baseFare: bigint;
}
export type DriverId = bigint;
export type CustomerId = bigint;
export interface AdminLog {
    id: AdminLogId;
    action: string;
    target: string;
    timestamp: Timestamp;
    details: string;
    adminId: string;
}
export enum CustomerStatus {
    active = "active",
    banned = "banned",
    suspended = "suspended"
}
export enum DiscountType {
    fixed = "fixed",
    percentage = "percentage"
}
export enum DriverRank {
    Diamond = "Diamond",
    Gold = "Gold",
    Platinum = "Platinum"
}
export enum DriverStatus {
    blocked = "blocked",
    suspended = "suspended",
    offline = "offline",
    onRide = "onRide",
    online = "online"
}
export enum PaymentMethod {
    cash = "cash",
    jazzCash = "jazzCash",
    easypaisa = "easypaisa",
    wallet = "wallet"
}
export enum PromoStatus {
    active = "active",
    inactive = "inactive"
}
export enum RideStatus {
    reached = "reached",
    cancelled = "cancelled",
    started = "started",
    completed = "completed",
    arriving = "arriving",
    accepted = "accepted",
    inProgress = "inProgress",
    searching = "searching"
}
export enum Variant_ok_notFound {
    ok = "ok",
    notFound = "notFound"
}
export enum VehicleType {
    Car = "Car",
    Premium = "Premium",
    Bike = "Bike",
    Rickshaw = "Rickshaw"
}
export interface backendInterface {
    addActivationCode(code: ActivationCode): Promise<ActivationCode>;
    addAdminLog(log: AdminLog): Promise<AdminLog>;
    addCustomer(customer: Customer): Promise<Customer>;
    addDriver(driver: Driver): Promise<Driver>;
    addPromoCode(promo: PromoCode): Promise<PromoCode>;
    addRide(ride: Ride): Promise<Ride>;
    getCustomer(id: CustomerId): Promise<Customer | null>;
    getDriver(id: DriverId): Promise<Driver | null>;
    getRide(id: RideId): Promise<Ride | null>;
    getWallet(driverId: DriverId): Promise<Wallet | null>;
    listActivationCodes(): Promise<Array<ActivationCode>>;
    listAdminLogs(): Promise<Array<AdminLog>>;
    listCustomers(): Promise<Array<Customer>>;
    listDrivers(): Promise<Array<Driver>>;
    listPromoCodes(): Promise<Array<PromoCode>>;
    listRides(): Promise<Array<Ride>>;
    listWallets(): Promise<Array<Wallet>>;
    updateCustomer(customer: Customer): Promise<Variant_ok_notFound>;
    updateDriver(driver: Driver): Promise<Variant_ok_notFound>;
    updatePromoCode(promo: PromoCode): Promise<Variant_ok_notFound>;
    updateRideStatus(id: RideId, status: RideStatus, completedAt: Timestamp | null, customerRating: bigint | null, driverRating: bigint | null, driverId: DriverId | null): Promise<Variant_ok_notFound>;
    updateWallet(wallet: Wallet): Promise<Wallet>;
    useActivationCode(code: string, usedBy: string): Promise<{
        __kind__: "ok";
        ok: ActivationCode;
    } | {
        __kind__: "alreadyUsed";
        alreadyUsed: null;
    } | {
        __kind__: "expired";
        expired: null;
    } | {
        __kind__: "notFound";
        notFound: null;
    }>;
}
import type { ActivationCode as _ActivationCode, ActivationCodeId as _ActivationCodeId, Customer as _Customer, CustomerId as _CustomerId, CustomerStatus as _CustomerStatus, DiscountType as _DiscountType, Driver as _Driver, DriverId as _DriverId, DriverRank as _DriverRank, DriverStatus as _DriverStatus, PaymentMethod as _PaymentMethod, PromoCode as _PromoCode, PromoCodeId as _PromoCodeId, PromoStatus as _PromoStatus, Ride as _Ride, RideId as _RideId, RideStatus as _RideStatus, Timestamp as _Timestamp, VehicleType as _VehicleType, Wallet as _Wallet } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addActivationCode(arg0: ActivationCode): Promise<ActivationCode> {
        if (this.processError) {
            try {
                const result = await this.actor.addActivationCode(to_candid_ActivationCode_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ActivationCode_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addActivationCode(to_candid_ActivationCode_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ActivationCode_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async addAdminLog(arg0: AdminLog): Promise<AdminLog> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdminLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdminLog(arg0);
            return result;
        }
    }
    async addCustomer(arg0: Customer): Promise<Customer> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomer(to_candid_Customer_n7(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Customer_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomer(to_candid_Customer_n7(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Customer_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async addDriver(arg0: Driver): Promise<Driver> {
        if (this.processError) {
            try {
                const result = await this.actor.addDriver(to_candid_Driver_n15(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Driver_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDriver(to_candid_Driver_n15(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Driver_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async addPromoCode(arg0: PromoCode): Promise<PromoCode> {
        if (this.processError) {
            try {
                const result = await this.actor.addPromoCode(to_candid_PromoCode_n31(this._uploadFile, this._downloadFile, arg0));
                return from_candid_PromoCode_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPromoCode(to_candid_PromoCode_n31(this._uploadFile, this._downloadFile, arg0));
            return from_candid_PromoCode_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async addRide(arg0: Ride): Promise<Ride> {
        if (this.processError) {
            try {
                const result = await this.actor.addRide(to_candid_Ride_n43(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Ride_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRide(to_candid_Ride_n43(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Ride_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomer(arg0: CustomerId): Promise<Customer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomer(arg0);
                return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomer(arg0);
            return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDriver(arg0: DriverId): Promise<Driver | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDriver(arg0);
                return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDriver(arg0);
            return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRide(arg0: RideId): Promise<Ride | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRide(arg0);
                return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRide(arg0);
            return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWallet(arg0: DriverId): Promise<Wallet | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWallet(arg0);
                return from_candid_opt_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWallet(arg0);
            return from_candid_opt_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async listActivationCodes(): Promise<Array<ActivationCode>> {
        if (this.processError) {
            try {
                const result = await this.actor.listActivationCodes();
                return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listActivationCodes();
            return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAdminLogs(): Promise<Array<AdminLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAdminLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAdminLogs();
            return result;
        }
    }
    async listCustomers(): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCustomers();
                return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCustomers();
            return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async listDrivers(): Promise<Array<Driver>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDrivers();
                return from_candid_vec_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDrivers();
            return from_candid_vec_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPromoCodes(): Promise<Array<PromoCode>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPromoCodes();
                return from_candid_vec_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPromoCodes();
            return from_candid_vec_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async listRides(): Promise<Array<Ride>> {
        if (this.processError) {
            try {
                const result = await this.actor.listRides();
                return from_candid_vec_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRides();
            return from_candid_vec_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async listWallets(): Promise<Array<Wallet>> {
        if (this.processError) {
            try {
                const result = await this.actor.listWallets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listWallets();
            return result;
        }
    }
    async updateCustomer(arg0: Customer): Promise<Variant_ok_notFound> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomer(to_candid_Customer_n7(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomer(to_candid_Customer_n7(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateDriver(arg0: Driver): Promise<Variant_ok_notFound> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDriver(to_candid_Driver_n15(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDriver(to_candid_Driver_n15(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePromoCode(arg0: PromoCode): Promise<Variant_ok_notFound> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePromoCode(to_candid_PromoCode_n31(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePromoCode(to_candid_PromoCode_n31(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateRideStatus(arg0: RideId, arg1: RideStatus, arg2: Timestamp | null, arg3: bigint | null, arg4: bigint | null, arg5: DriverId | null): Promise<Variant_ok_notFound> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRideStatus(arg0, to_candid_RideStatus_n45(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n67(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n68(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n68(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n69(this._uploadFile, this._downloadFile, arg5));
                return from_candid_variant_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRideStatus(arg0, to_candid_RideStatus_n45(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n67(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n68(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n68(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n69(this._uploadFile, this._downloadFile, arg5));
            return from_candid_variant_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateWallet(arg0: Wallet): Promise<Wallet> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWallet(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWallet(arg0);
            return result;
        }
    }
    async useActivationCode(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: ActivationCode;
    } | {
        __kind__: "alreadyUsed";
        alreadyUsed: null;
    } | {
        __kind__: "expired";
        expired: null;
    } | {
        __kind__: "notFound";
        notFound: null;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.useActivationCode(arg0, arg1);
                return from_candid_variant_n70(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.useActivationCode(arg0, arg1);
            return from_candid_variant_n70(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ActivationCode_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivationCode): ActivationCode {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_CustomerStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CustomerStatus): CustomerStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Customer_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Customer): Customer {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_DiscountType_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DiscountType): DiscountType {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_DriverRank_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DriverRank): DriverRank {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_DriverStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DriverStatus): DriverStatus {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Driver_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Driver): Driver {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function from_candid_PromoCode_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PromoCode): PromoCode {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_PromoStatus_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PromoStatus): PromoStatus {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_RideStatus_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RideStatus): RideStatus {
    return from_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function from_candid_Ride_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Ride): Ride {
    return from_candid_record_n50(_uploadFile, _downloadFile, value);
}
function from_candid_VehicleType_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VehicleType): VehicleType {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DriverId]): DriverId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Customer]): Customer | null {
    return value.length === 0 ? null : from_candid_Customer_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Driver]): Driver | null {
    return value.length === 0 ? null : from_candid_Driver_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Ride]): Ride | null {
    return value.length === 0 ? null : from_candid_Ride_n49(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Wallet]): Wallet | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CustomerId;
    status: _CustomerStatus;
    joinDate: _Timestamp;
    name: string;
    email: string;
    phone: string;
    walletBalance: bigint;
    totalRides: bigint;
}): {
    id: CustomerId;
    status: CustomerStatus;
    joinDate: Timestamp;
    name: string;
    email: string;
    phone: string;
    walletBalance: bigint;
    totalRides: bigint;
} {
    return {
        id: value.id,
        status: from_candid_CustomerStatus_n13(_uploadFile, _downloadFile, value.status),
        joinDate: value.joinDate,
        name: value.name,
        email: value.email,
        phone: value.phone,
        walletBalance: value.walletBalance,
        totalRides: value.totalRides
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _DriverId;
    status: _DriverStatus;
    vehicleType: _VehicleType;
    vehiclePlate: string;
    cnic: string;
    name: string;
    rank: _DriverRank;
    vehicleModel: string;
    licenseNumber: string;
    vehicleColor: string;
    rating: number;
    phone: string;
    activationCode: string;
    walletBalance: bigint;
    totalRides: bigint;
}): {
    id: DriverId;
    status: DriverStatus;
    vehicleType: VehicleType;
    vehiclePlate: string;
    cnic: string;
    name: string;
    rank: DriverRank;
    vehicleModel: string;
    licenseNumber: string;
    vehicleColor: string;
    rating: number;
    phone: string;
    activationCode: string;
    walletBalance: bigint;
    totalRides: bigint;
} {
    return {
        id: value.id,
        status: from_candid_DriverStatus_n25(_uploadFile, _downloadFile, value.status),
        vehicleType: from_candid_VehicleType_n27(_uploadFile, _downloadFile, value.vehicleType),
        vehiclePlate: value.vehiclePlate,
        cnic: value.cnic,
        name: value.name,
        rank: from_candid_DriverRank_n29(_uploadFile, _downloadFile, value.rank),
        vehicleModel: value.vehicleModel,
        licenseNumber: value.licenseNumber,
        vehicleColor: value.vehicleColor,
        rating: value.rating,
        phone: value.phone,
        activationCode: value.activationCode,
        walletBalance: value.walletBalance,
        totalRides: value.totalRides
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PromoCodeId;
    status: _PromoStatus;
    expiryDate: _Timestamp;
    code: string;
    discountAmount: bigint;
    discountType: _DiscountType;
    usageCount: bigint;
    usageLimit: bigint;
}): {
    id: PromoCodeId;
    status: PromoStatus;
    expiryDate: Timestamp;
    code: string;
    discountAmount: bigint;
    discountType: DiscountType;
    usageCount: bigint;
    usageLimit: bigint;
} {
    return {
        id: value.id,
        status: from_candid_PromoStatus_n39(_uploadFile, _downloadFile, value.status),
        expiryDate: value.expiryDate,
        code: value.code,
        discountAmount: value.discountAmount,
        discountType: from_candid_DiscountType_n41(_uploadFile, _downloadFile, value.discountType),
        usageCount: value.usageCount,
        usageLimit: value.usageLimit
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ActivationCodeId;
    expiryDate: _Timestamp;
    code: string;
    usedAt: [] | [_Timestamp];
    usedBy: [] | [string];
    used: boolean;
}): {
    id: ActivationCodeId;
    expiryDate: Timestamp;
    code: string;
    usedAt?: Timestamp;
    usedBy?: string;
    used: boolean;
} {
    return {
        id: value.id,
        expiryDate: value.expiryDate,
        code: value.code,
        usedAt: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.usedAt)),
        usedBy: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.usedBy)),
        used: value.used
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RideId;
    otp: string;
    status: _RideStatus;
    dropLat: number;
    dropLng: number;
    completedAt: [] | [_Timestamp];
    driverId: [] | [_DriverId];
    vehicleType: _VehicleType;
    paymentMethod: _PaymentMethod;
    driverRating: [] | [bigint];
    pickupLat: number;
    pickupLng: number;
    createdAt: _Timestamp;
    customerRating: [] | [bigint];
    totalFare: bigint;
    pickupAddress: string;
    customerId: _CustomerId;
    dropAddress: string;
    distanceFare: bigint;
    baseFare: bigint;
}): {
    id: RideId;
    otp: string;
    status: RideStatus;
    dropLat: number;
    dropLng: number;
    completedAt?: Timestamp;
    driverId?: DriverId;
    vehicleType: VehicleType;
    paymentMethod: PaymentMethod;
    driverRating?: bigint;
    pickupLat: number;
    pickupLng: number;
    createdAt: Timestamp;
    customerRating?: bigint;
    totalFare: bigint;
    pickupAddress: string;
    customerId: CustomerId;
    dropAddress: string;
    distanceFare: bigint;
    baseFare: bigint;
} {
    return {
        id: value.id,
        otp: value.otp,
        status: from_candid_RideStatus_n51(_uploadFile, _downloadFile, value.status),
        dropLat: value.dropLat,
        dropLng: value.dropLng,
        completedAt: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.completedAt)),
        driverId: record_opt_to_undefined(from_candid_opt_n53(_uploadFile, _downloadFile, value.driverId)),
        vehicleType: from_candid_VehicleType_n27(_uploadFile, _downloadFile, value.vehicleType),
        paymentMethod: from_candid_PaymentMethod_n54(_uploadFile, _downloadFile, value.paymentMethod),
        driverRating: record_opt_to_undefined(from_candid_opt_n56(_uploadFile, _downloadFile, value.driverRating)),
        pickupLat: value.pickupLat,
        pickupLng: value.pickupLng,
        createdAt: value.createdAt,
        customerRating: record_opt_to_undefined(from_candid_opt_n56(_uploadFile, _downloadFile, value.customerRating)),
        totalFare: value.totalFare,
        pickupAddress: value.pickupAddress,
        customerId: value.customerId,
        dropAddress: value.dropAddress,
        distanceFare: value.distanceFare,
        baseFare: value.baseFare
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    banned: null;
} | {
    suspended: null;
}): CustomerStatus {
    return "active" in value ? CustomerStatus.active : "banned" in value ? CustomerStatus.banned : "suspended" in value ? CustomerStatus.suspended : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blocked: null;
} | {
    suspended: null;
} | {
    offline: null;
} | {
    onRide: null;
} | {
    online: null;
}): DriverStatus {
    return "blocked" in value ? DriverStatus.blocked : "suspended" in value ? DriverStatus.suspended : "offline" in value ? DriverStatus.offline : "onRide" in value ? DriverStatus.onRide : "online" in value ? DriverStatus.online : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Car: null;
} | {
    Premium: null;
} | {
    Bike: null;
} | {
    Rickshaw: null;
}): VehicleType {
    return "Car" in value ? VehicleType.Car : "Premium" in value ? VehicleType.Premium : "Bike" in value ? VehicleType.Bike : "Rickshaw" in value ? VehicleType.Rickshaw : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Diamond: null;
} | {
    Gold: null;
} | {
    Platinum: null;
}): DriverRank {
    return "Diamond" in value ? DriverRank.Diamond : "Gold" in value ? DriverRank.Gold : "Platinum" in value ? DriverRank.Platinum : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    inactive: null;
}): PromoStatus {
    return "active" in value ? PromoStatus.active : "inactive" in value ? PromoStatus.inactive : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fixed: null;
} | {
    percentage: null;
}): DiscountType {
    return "fixed" in value ? DiscountType.fixed : "percentage" in value ? DiscountType.percentage : value;
}
function from_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    reached: null;
} | {
    cancelled: null;
} | {
    started: null;
} | {
    completed: null;
} | {
    arriving: null;
} | {
    accepted: null;
} | {
    inProgress: null;
} | {
    searching: null;
}): RideStatus {
    return "reached" in value ? RideStatus.reached : "cancelled" in value ? RideStatus.cancelled : "started" in value ? RideStatus.started : "completed" in value ? RideStatus.completed : "arriving" in value ? RideStatus.arriving : "accepted" in value ? RideStatus.accepted : "inProgress" in value ? RideStatus.inProgress : "searching" in value ? RideStatus.searching : value;
}
function from_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cash: null;
} | {
    jazzCash: null;
} | {
    easypaisa: null;
} | {
    wallet: null;
}): PaymentMethod {
    return "cash" in value ? PaymentMethod.cash : "jazzCash" in value ? PaymentMethod.jazzCash : "easypaisa" in value ? PaymentMethod.easypaisa : "wallet" in value ? PaymentMethod.wallet : value;
}
function from_candid_variant_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    notFound: null;
}): Variant_ok_notFound {
    return "ok" in value ? Variant_ok_notFound.ok : "notFound" in value ? Variant_ok_notFound.notFound : value;
}
function from_candid_variant_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ActivationCode;
} | {
    alreadyUsed: null;
} | {
    expired: null;
} | {
    notFound: null;
}): {
    __kind__: "ok";
    ok: ActivationCode;
} | {
    __kind__: "alreadyUsed";
    alreadyUsed: null;
} | {
    __kind__: "expired";
    expired: null;
} | {
    __kind__: "notFound";
    notFound: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_ActivationCode_n3(_uploadFile, _downloadFile, value.ok)
    } : "alreadyUsed" in value ? {
        __kind__: "alreadyUsed",
        alreadyUsed: value.alreadyUsed
    } : "expired" in value ? {
        __kind__: "expired",
        expired: value.expired
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : value;
}
function from_candid_vec_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ActivationCode>): Array<ActivationCode> {
    return value.map((x)=>from_candid_ActivationCode_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Customer>): Array<Customer> {
    return value.map((x)=>from_candid_Customer_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Driver>): Array<Driver> {
    return value.map((x)=>from_candid_Driver_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PromoCode>): Array<PromoCode> {
    return value.map((x)=>from_candid_PromoCode_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Ride>): Array<Ride> {
    return value.map((x)=>from_candid_Ride_n49(_uploadFile, _downloadFile, x));
}
function to_candid_ActivationCode_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivationCode): _ActivationCode {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_CustomerStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CustomerStatus): _CustomerStatus {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_Customer_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Customer): _Customer {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_DiscountType_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DiscountType): _DiscountType {
    return to_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function to_candid_DriverRank_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DriverRank): _DriverRank {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_DriverStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DriverStatus): _DriverStatus {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_Driver_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Driver): _Driver {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function to_candid_PromoCode_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PromoCode): _PromoCode {
    return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid_PromoStatus_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PromoStatus): _PromoStatus {
    return to_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function to_candid_RideStatus_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RideStatus): _RideStatus {
    return to_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function to_candid_Ride_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Ride): _Ride {
    return to_candid_record_n44(_uploadFile, _downloadFile, value);
}
function to_candid_VehicleType_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleType): _VehicleType {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Timestamp | null): [] | [_Timestamp] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DriverId | null): [] | [_DriverId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: DriverId;
    status: DriverStatus;
    vehicleType: VehicleType;
    vehiclePlate: string;
    cnic: string;
    name: string;
    rank: DriverRank;
    vehicleModel: string;
    licenseNumber: string;
    vehicleColor: string;
    rating: number;
    phone: string;
    activationCode: string;
    walletBalance: bigint;
    totalRides: bigint;
}): {
    id: _DriverId;
    status: _DriverStatus;
    vehicleType: _VehicleType;
    vehiclePlate: string;
    cnic: string;
    name: string;
    rank: _DriverRank;
    vehicleModel: string;
    licenseNumber: string;
    vehicleColor: string;
    rating: number;
    phone: string;
    activationCode: string;
    walletBalance: bigint;
    totalRides: bigint;
} {
    return {
        id: value.id,
        status: to_candid_DriverStatus_n17(_uploadFile, _downloadFile, value.status),
        vehicleType: to_candid_VehicleType_n19(_uploadFile, _downloadFile, value.vehicleType),
        vehiclePlate: value.vehiclePlate,
        cnic: value.cnic,
        name: value.name,
        rank: to_candid_DriverRank_n21(_uploadFile, _downloadFile, value.rank),
        vehicleModel: value.vehicleModel,
        licenseNumber: value.licenseNumber,
        vehicleColor: value.vehicleColor,
        rating: value.rating,
        phone: value.phone,
        activationCode: value.activationCode,
        walletBalance: value.walletBalance,
        totalRides: value.totalRides
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: ActivationCodeId;
    expiryDate: Timestamp;
    code: string;
    usedAt?: Timestamp;
    usedBy?: string;
    used: boolean;
}): {
    id: _ActivationCodeId;
    expiryDate: _Timestamp;
    code: string;
    usedAt: [] | [_Timestamp];
    usedBy: [] | [string];
    used: boolean;
} {
    return {
        id: value.id,
        expiryDate: value.expiryDate,
        code: value.code,
        usedAt: value.usedAt ? candid_some(value.usedAt) : candid_none(),
        usedBy: value.usedBy ? candid_some(value.usedBy) : candid_none(),
        used: value.used
    };
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: PromoCodeId;
    status: PromoStatus;
    expiryDate: Timestamp;
    code: string;
    discountAmount: bigint;
    discountType: DiscountType;
    usageCount: bigint;
    usageLimit: bigint;
}): {
    id: _PromoCodeId;
    status: _PromoStatus;
    expiryDate: _Timestamp;
    code: string;
    discountAmount: bigint;
    discountType: _DiscountType;
    usageCount: bigint;
    usageLimit: bigint;
} {
    return {
        id: value.id,
        status: to_candid_PromoStatus_n33(_uploadFile, _downloadFile, value.status),
        expiryDate: value.expiryDate,
        code: value.code,
        discountAmount: value.discountAmount,
        discountType: to_candid_DiscountType_n35(_uploadFile, _downloadFile, value.discountType),
        usageCount: value.usageCount,
        usageLimit: value.usageLimit
    };
}
function to_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: RideId;
    otp: string;
    status: RideStatus;
    dropLat: number;
    dropLng: number;
    completedAt?: Timestamp;
    driverId?: DriverId;
    vehicleType: VehicleType;
    paymentMethod: PaymentMethod;
    driverRating?: bigint;
    pickupLat: number;
    pickupLng: number;
    createdAt: Timestamp;
    customerRating?: bigint;
    totalFare: bigint;
    pickupAddress: string;
    customerId: CustomerId;
    dropAddress: string;
    distanceFare: bigint;
    baseFare: bigint;
}): {
    id: _RideId;
    otp: string;
    status: _RideStatus;
    dropLat: number;
    dropLng: number;
    completedAt: [] | [_Timestamp];
    driverId: [] | [_DriverId];
    vehicleType: _VehicleType;
    paymentMethod: _PaymentMethod;
    driverRating: [] | [bigint];
    pickupLat: number;
    pickupLng: number;
    createdAt: _Timestamp;
    customerRating: [] | [bigint];
    totalFare: bigint;
    pickupAddress: string;
    customerId: _CustomerId;
    dropAddress: string;
    distanceFare: bigint;
    baseFare: bigint;
} {
    return {
        id: value.id,
        otp: value.otp,
        status: to_candid_RideStatus_n45(_uploadFile, _downloadFile, value.status),
        dropLat: value.dropLat,
        dropLng: value.dropLng,
        completedAt: value.completedAt ? candid_some(value.completedAt) : candid_none(),
        driverId: value.driverId ? candid_some(value.driverId) : candid_none(),
        vehicleType: to_candid_VehicleType_n19(_uploadFile, _downloadFile, value.vehicleType),
        paymentMethod: to_candid_PaymentMethod_n47(_uploadFile, _downloadFile, value.paymentMethod),
        driverRating: value.driverRating ? candid_some(value.driverRating) : candid_none(),
        pickupLat: value.pickupLat,
        pickupLng: value.pickupLng,
        createdAt: value.createdAt,
        customerRating: value.customerRating ? candid_some(value.customerRating) : candid_none(),
        totalFare: value.totalFare,
        pickupAddress: value.pickupAddress,
        customerId: value.customerId,
        dropAddress: value.dropAddress,
        distanceFare: value.distanceFare,
        baseFare: value.baseFare
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: CustomerId;
    status: CustomerStatus;
    joinDate: Timestamp;
    name: string;
    email: string;
    phone: string;
    walletBalance: bigint;
    totalRides: bigint;
}): {
    id: _CustomerId;
    status: _CustomerStatus;
    joinDate: _Timestamp;
    name: string;
    email: string;
    phone: string;
    walletBalance: bigint;
    totalRides: bigint;
} {
    return {
        id: value.id,
        status: to_candid_CustomerStatus_n9(_uploadFile, _downloadFile, value.status),
        joinDate: value.joinDate,
        name: value.name,
        email: value.email,
        phone: value.phone,
        walletBalance: value.walletBalance,
        totalRides: value.totalRides
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CustomerStatus): {
    active: null;
} | {
    banned: null;
} | {
    suspended: null;
} {
    return value == CustomerStatus.active ? {
        active: null
    } : value == CustomerStatus.banned ? {
        banned: null
    } : value == CustomerStatus.suspended ? {
        suspended: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DriverStatus): {
    blocked: null;
} | {
    suspended: null;
} | {
    offline: null;
} | {
    onRide: null;
} | {
    online: null;
} {
    return value == DriverStatus.blocked ? {
        blocked: null
    } : value == DriverStatus.suspended ? {
        suspended: null
    } : value == DriverStatus.offline ? {
        offline: null
    } : value == DriverStatus.onRide ? {
        onRide: null
    } : value == DriverStatus.online ? {
        online: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleType): {
    Car: null;
} | {
    Premium: null;
} | {
    Bike: null;
} | {
    Rickshaw: null;
} {
    return value == VehicleType.Car ? {
        Car: null
    } : value == VehicleType.Premium ? {
        Premium: null
    } : value == VehicleType.Bike ? {
        Bike: null
    } : value == VehicleType.Rickshaw ? {
        Rickshaw: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DriverRank): {
    Diamond: null;
} | {
    Gold: null;
} | {
    Platinum: null;
} {
    return value == DriverRank.Diamond ? {
        Diamond: null
    } : value == DriverRank.Gold ? {
        Gold: null
    } : value == DriverRank.Platinum ? {
        Platinum: null
    } : value;
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PromoStatus): {
    active: null;
} | {
    inactive: null;
} {
    return value == PromoStatus.active ? {
        active: null
    } : value == PromoStatus.inactive ? {
        inactive: null
    } : value;
}
function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DiscountType): {
    fixed: null;
} | {
    percentage: null;
} {
    return value == DiscountType.fixed ? {
        fixed: null
    } : value == DiscountType.percentage ? {
        percentage: null
    } : value;
}
function to_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RideStatus): {
    reached: null;
} | {
    cancelled: null;
} | {
    started: null;
} | {
    completed: null;
} | {
    arriving: null;
} | {
    accepted: null;
} | {
    inProgress: null;
} | {
    searching: null;
} {
    return value == RideStatus.reached ? {
        reached: null
    } : value == RideStatus.cancelled ? {
        cancelled: null
    } : value == RideStatus.started ? {
        started: null
    } : value == RideStatus.completed ? {
        completed: null
    } : value == RideStatus.arriving ? {
        arriving: null
    } : value == RideStatus.accepted ? {
        accepted: null
    } : value == RideStatus.inProgress ? {
        inProgress: null
    } : value == RideStatus.searching ? {
        searching: null
    } : value;
}
function to_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    cash: null;
} | {
    jazzCash: null;
} | {
    easypaisa: null;
} | {
    wallet: null;
} {
    return value == PaymentMethod.cash ? {
        cash: null
    } : value == PaymentMethod.jazzCash ? {
        jazzCash: null
    } : value == PaymentMethod.easypaisa ? {
        easypaisa: null
    } : value == PaymentMethod.wallet ? {
        wallet: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
